<footer class="footer">
      <div class="container">
        <p class="text-muted">This is a great footer.</p>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://localhost/phpApp/assets/js/bootstrap.min.js"></script>
  </body>
</html>